name: Build & Publish LIBRA App Spec
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: dev
    env:
      #LIBRA_TAG: "ghcr.io/libra-release/libra:v1"
      LIBRA_APP_TAG: "ghcr.io/libra-release/libra:app"
    steps:
      - uses: actions/checkout@v2
      - name: Container Img Building
        run: |
          docker build -t $LIBRA_APP_TAG -f ./oci/app.Docker .
      - name: Container Images Deployment
        env:
          MY_REGISTRY_ID: ${{secrets.MY_GITHUB_ID}}
          MY_REGISTRY_TKN: ${{secrets.MY_GITHUB_TKN}}
          MY_REGISTRY: "https://ghcr.io"
        run: |
          echo $MY_REGISTRY_TKN | docker login $MY_REGISTRY -u $MY_REGISTRY_ID --password-stdin
          docker push $LIBRA_APP_TAG
